<div class="b-form__field<?= $this->modsClass($mods) ?>">
	<input type="checkbox" name="<?= $this->name() ?>" class="b-form__input b-form__input--checkbox"
		<?php if ($id = $this->inputId()) { ?>
			id="<?= $id ?>"
		<?php } ?>
		
		<?php if ($this->isRequired()) { ?>
			data-validate-presence-message="<?= $this->requiredErrorMessage() ?>"
		<?php } ?>
	>
	<label class="b-form__label" for="<?= $this->inputId() ?>"><?= $this->label() ?></label>
</div>