<div class="b-form__field<?= $this->modsClass($mods) ?>">
	<input class="b-form__input" name="<?= $this->name() ?>" type="text" placeholder="<?= $this->placeholder() ?>"
		
		<?php if ($id = $this->inputId()) { ?>
			id="<?= $id ?>"
		<?php } ?>
		
		<?php if ($this->isRequired()) { ?>
			required data-validate-presence-message="<?= $this->requiredErrorMessage() ?>"
		<?php } ?>
		
		<?php if ($this->isEmail()) { ?>
			required data-validate-email-message="<?= $this->emailErrorMessage() ?>"
		<?php } ?>
		
		<?php if ($this->isDisabled()) { ?>
			dispabled
		<?php } ?>
	>
	<label class="b-form__label" for="<?= $this->inputId() ?>"><?= $this->label() ?></label>
</div>
