<div class="b-form__field<?= $this->modsClass($mods) ?>">
	<textarea class="b-form__input b-form__input--textarea" name="<?= $this->name() ?>" rows="1" placeholder="<?= $this->placeholder() ?>"
		
		<?php if ($id = $this->inputId()) { ?>
			id="<?= $id ?>"
		<?php } ?>
		
		<?php if ($this->isRequired()) { ?>
			required data-validate-presence-message="<?= $this->requiredErrorMessage() ?>"
		<?php } ?>
		
		<?php if ($this->isDisabled()) { ?>
			dispabled
		<?php } ?>
	></textarea>
	<label class="b-form__label" for="<?= $this->inputId() ?>"><?= $this->label() ?></label>
</div>
