<div class="tao-form tao-form-<?= $name ?>">
    <ul class="tao-form-errors"<?= (count($this->errors)>0? '' : ' style="display: none;"') ?>>
        <?php foreach($this->errors as $field => $error) if (strlen($error)>1) { ?>
            <li data-field="<?= $field ?>" class="error-field-<?= $field ?>"><?= $error ?></li>
        <?php } ?>
    </ul>
    <form id="tao-form-<?= $name ?>" method="post" action="<?= $action ?>" class="tao-form tao-form-<?= $name ?>"<?= ($this->multipart? ' enctype="multipart/form-data"' : '') ?>>
        <input type="hidden" name="taoform" value="<?= $name ?>">
        <?php foreach($fields as $field => $data) if ($this->fieldType($field) == 'hidden') {
            print $data['input'];
        } ?>
        <?php include($templateLayout); ?>
    </form>
    <?php if ($this->ajax()) { ?>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                taoAjaxForm('<?= $name ?>', <?= json_encode($this->options) ?>);
            });
        </script>
    <?php } ?>
</div>
